server:
  port: ${server.port.cache:8080}

spring:
  application:
    name: ${server.name.cache:cache}
  profiles:
    include: base
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10s
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: redis
  session:
    store-type: redis