server:
  port: 10001

spring:
  application:
    name: server_config_center
  #配置读取本地文件
  profiles:
    active: native
  #配置基础的安全认证
  security:
    user:
      name: roy
      password: GTI5FHvSYBf2c=

#动态刷新配置 ---需要忽略权限拦截
management:
  security:
    enabled: true