server:
  port: 10001

spring:
  application:
    name: server_config_center
  #配置读取本地文件
  profiles:
    active: native
  security:
    user:
      name: roy
      password: 123456

management:
  security:
    enabled: true