server:
  port: 10001

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

spring:
  application:
    name: config-server
  #配置读取本地文件
  profiles:
    active: native
  cloud:
    #/{label}/{application}-{profile}:properties:
    #spring.application.name：对应配置文件规则中的{application}部分
    #spring.cloud.config.profile：对应配置文件规则中的{profile}部分
    #spring.cloud.config.label：对应配置文件规则中的{label}部分
    #spring.cloud.config.uri：配置中心config-server的地址
    config:
      server:
        native:
          #注意，Windows中的绝对路径需要额外的“/”
          search-locations: /Users/zzy/code/J2EEProject/ConfigCenter
  #配置读取远程仓库文件
#  cloud:
#    config:
#      #配置仓库分支
#      label: master
#      #配置远程仓库
#      server:
#        git:
#          #仓库地址
#          uri: https://github.com/zhouyige66/ConfigCenter.git
#          #仓库路径
#          searchPaths: /**
#          username: 751664206@qq.com
#          password: kk209257@g
#          #跳过ssl认证
#          skip-ssl-validation: true
#          #启动时候clone仓库
#          clone-on-start: true
#          order: 2
