package cn.roy.springcloud.api.dao.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   接口表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table api
 */
public class Api implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.id
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   接口名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.name
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private String name;

    /**
     * Database Column Remarks:
     *   对应Controller
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.controller
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private String controller;

    /**
     * Database Column Remarks:
     *   接口描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.description
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private String description;

    /**
     * Database Column Remarks:
     *   路由
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.route
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private String route;

    /**
     * Database Column Remarks:
     *   请求方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.method
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private String method;

    /**
     * Database Column Remarks:
     *   请求参数id，逗号分隔
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.parameterIds
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private String parameterids;

    /**
     * Database Column Remarks:
     *   entity id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.body
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Long body;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.del
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Boolean del;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.create_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.update_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.id
     *
     * @return the value of api.id
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.id
     *
     * @param id the value for api.id
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.name
     *
     * @return the value of api.name
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.name
     *
     * @param name the value for api.name
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.controller
     *
     * @return the value of api.controller
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public String getController() {
        return controller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withController(String controller) {
        this.setController(controller);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.controller
     *
     * @param controller the value for api.controller
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setController(String controller) {
        this.controller = controller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.description
     *
     * @return the value of api.description
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.description
     *
     * @param description the value for api.description
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.route
     *
     * @return the value of api.route
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withRoute(String route) {
        this.setRoute(route);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.route
     *
     * @param route the value for api.route
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setRoute(String route) {
        this.route = route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.method
     *
     * @return the value of api.method
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withMethod(String method) {
        this.setMethod(method);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.method
     *
     * @param method the value for api.method
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.parameterIds
     *
     * @return the value of api.parameterIds
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public String getParameterids() {
        return parameterids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withParameterids(String parameterids) {
        this.setParameterids(parameterids);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.parameterIds
     *
     * @param parameterids the value for api.parameterIds
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setParameterids(String parameterids) {
        this.parameterids = parameterids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.body
     *
     * @return the value of api.body
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Long getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withBody(Long body) {
        this.setBody(body);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.body
     *
     * @param body the value for api.body
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setBody(Long body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.del
     *
     * @return the value of api.del
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withDel(Boolean del) {
        this.setDel(del);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.del
     *
     * @param del the value for api.del
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.create_time
     *
     * @return the value of api.create_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.create_time
     *
     * @param createTime the value for api.create_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.update_time
     *
     * @return the value of api.update_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Api withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.update_time
     *
     * @param updateTime the value for api.update_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", controller=").append(controller);
        sb.append(", description=").append(description);
        sb.append(", route=").append(route);
        sb.append(", method=").append(method);
        sb.append(", parameterids=").append(parameterids);
        sb.append(", body=").append(body);
        sb.append(", del=").append(del);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}