package cn.roy.springcloud.api.dao.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   接口调用计数表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table api_count
 */
public class ApiCount implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.id
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   实体名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.api_id
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Long apiId;

    /**
     * Database Column Remarks:
     *   耗时
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.cost_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Long costTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.delete
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Boolean delete;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.create_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.update_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.id
     *
     * @return the value of api_count.id
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public ApiCount withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.id
     *
     * @param id the value for api_count.id
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.api_id
     *
     * @return the value of api_count.api_id
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Long getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public ApiCount withApiId(Long apiId) {
        this.setApiId(apiId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.api_id
     *
     * @param apiId the value for api_count.api_id
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setApiId(Long apiId) {
        this.apiId = apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.cost_time
     *
     * @return the value of api_count.cost_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Long getCostTime() {
        return costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public ApiCount withCostTime(Long costTime) {
        this.setCostTime(costTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.cost_time
     *
     * @param costTime the value for api_count.cost_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setCostTime(Long costTime) {
        this.costTime = costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.delete
     *
     * @return the value of api_count.delete
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Boolean getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public ApiCount withDelete(Boolean delete) {
        this.setDelete(delete);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.delete
     *
     * @param delete the value for api_count.delete
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setDelete(Boolean delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.create_time
     *
     * @return the value of api_count.create_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public ApiCount withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.create_time
     *
     * @param createTime the value for api_count.create_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.update_time
     *
     * @return the value of api_count.update_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public ApiCount withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.update_time
     *
     * @param updateTime the value for api_count.update_time
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", apiId=").append(apiId);
        sb.append(", costTime=").append(costTime);
        sb.append(", delete=").append(delete);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}