package cn.roy.springcloud.api.dao.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   接口表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table parameter
 */
public class Parameter implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.id
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   参数名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.name
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    private String name;

    /**
     * Database Column Remarks:
     *   参数描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.description
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    private String description;

    /**
     * Database Column Remarks:
     *   参数类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.type
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    private String type;

    /**
     * Database Column Remarks:
     *   是否必填
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.required
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    private Boolean required;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.del
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    private Boolean del;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.create_time
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.update_time
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.id
     *
     * @return the value of parameter.id
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Parameter withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.id
     *
     * @param id the value for parameter.id
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.name
     *
     * @return the value of parameter.name
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Parameter withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.name
     *
     * @param name the value for parameter.name
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.description
     *
     * @return the value of parameter.description
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Parameter withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.description
     *
     * @param description the value for parameter.description
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.type
     *
     * @return the value of parameter.type
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Parameter withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.type
     *
     * @param type the value for parameter.type
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.required
     *
     * @return the value of parameter.required
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Boolean getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Parameter withRequired(Boolean required) {
        this.setRequired(required);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.required
     *
     * @param required the value for parameter.required
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public void setRequired(Boolean required) {
        this.required = required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.del
     *
     * @return the value of parameter.del
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Parameter withDel(Boolean del) {
        this.setDel(del);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.del
     *
     * @param del the value for parameter.del
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.create_time
     *
     * @return the value of parameter.create_time
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Parameter withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.create_time
     *
     * @param createTime the value for parameter.create_time
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.update_time
     *
     * @return the value of parameter.update_time
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public Parameter withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.update_time
     *
     * @param updateTime the value for parameter.update_time
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", type=").append(type);
        sb.append(", required=").append(required);
        sb.append(", del=").append(del);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}