package cn.roy.springcloud.api.dao.mapper;

import cn.roy.springcloud.api.dao.bean.ApiCount;
import cn.roy.springcloud.api.dao.bean.ApiCountQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    long countByExample(ApiCountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int deleteByExample(ApiCountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int insert(ApiCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int insertSelective(ApiCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    List<ApiCount> selectByExample(ApiCountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    ApiCount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") ApiCount record, @Param("example") ApiCountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByExample(@Param("record") ApiCount record, @Param("example") ApiCountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByPrimaryKeySelective(ApiCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByPrimaryKey(ApiCount record);
}