package cn.roy.springcloud.api.dao.mapper;

import cn.roy.springcloud.api.dao.bean.Api;
import cn.roy.springcloud.api.dao.bean.ApiQuery;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    long countByExample(ApiQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int deleteByExample(ApiQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int insert(Api record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int insertSelective(Api record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    List<Api> selectByExample(ApiQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    Api selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") Api record, @Param("example") ApiQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByExample(@Param("record") Api record, @Param("example") ApiQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByPrimaryKeySelective(Api record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByPrimaryKey(Api record);

}