package cn.roy.springcloud.api.dao.mapper;

import cn.roy.springcloud.api.dao.bean.Entity;
import cn.roy.springcloud.api.dao.bean.EntityQuery;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    long countByExample(EntityQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int deleteByExample(EntityQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int insert(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int insertSelective(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    List<Entity> selectByExample(EntityQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    Entity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") Entity record, @Param("example") EntityQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByExample(@Param("record") Entity record, @Param("example") EntityQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByPrimaryKeySelective(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbg.generated Fri Sep 06 13:05:52 CST 2019
     */
    int updateByPrimaryKey(Entity record);
}