package cn.roy.springcloud.api.dao.mapper;

import cn.roy.springcloud.api.dao.bean.Parameter;
import cn.roy.springcloud.api.dao.bean.ParameterQuery;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    long countByExample(ParameterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    int deleteByExample(ParameterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    int insert(Parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    int insertSelective(Parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    List<Parameter> selectByExample(ParameterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    Parameter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Parameter record, @Param("example") ParameterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    int updateByExample(@Param("record") Parameter record, @Param("example") ParameterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    int updateByPrimaryKeySelective(Parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbg.generated Fri Sep 06 13:07:24 CST 2019
     */
    int updateByPrimaryKey(Parameter record);
}