server:
  port: 8765
spring:
  application:
    name: gateway

# 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

# 路由配置
zuul:
  routes:
    api:
      path: /api/**
      serviceId: api
    api2:
      path: /api2/**
      serviceId: api2
