server:
  port: 8761

#/{label}/{application}-{profile}:properties:
#spring.application.name：对应配置文件规则中的{application}部分
#spring.cloud.config.profile：对应配置文件规则中的{profile}部分
#spring.cloud.config.label：对应配置文件规则中的{label}部分
#spring.cloud.config.uri：配置中心config-server的地址
spring:
  application:
    name: api
  cloud:
    config:
      #配置当不能连接配置服务器，则不能启动
      fail-fast: true
      #配置仓库分支
      label: master
      #配置文件的环境
      profile: dev
      #使用uri
      uri: http://localhost:8888/
      #或discovery
#      discovery:
#        #开启配置服务发现
#        enabled: true
#        #注册中心的服务名
#        service-id: config-server
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      #additional-paths: src/main/java
  freemarker:
    template-loader-path: classpath:/templates/freemarker/
    #关闭缓存，即时刷新，上线前要更改为true
    cache: false
  thymeleaf:
    #关闭缓存，即时刷新，上线前要更改为true
    cache: false
    check-template-location: true
    prefix: classpath:/templates/thymeleaf/
  #邮箱配置
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    username: 751664206@qq.com
    password: kk20910925@q
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include=*:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
