server:
  port: 8760

eureka:
  instance:
    hostname: localhost
  client:
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # 注册中心安全验证，配置的地址格式为：http://<username>:<password>@<host>:<port>/<servername>
      # 其中<username>为安全校验的用户名，<password>为该用户的密码
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/