server:
  port: 8760

eureka:
  instance:
    hostname: localhost
  client:
    # 通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # 注册中心安全验证，配置的地址格式为：http://<username>:<password>@localhost:8761/eureka
      # 其中<username>为安全校验的用户名；<password>为该用户的密码
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#    # 自定义实例编号
#  instance:
#    # 服务实体注册名默认是“IP名:应用名:应用端口名”，可使用@value@读取maven中配置的属性
#    instance-id: ${spring.application.name}:${server.port}:'@project.version@'
#    # 配置使用主机名注册服务，需要更改/etc/hosts文件
#    hostname: node1
#    # 优先使用IP地址方式进行注册服务
#    prefer-ip-address: true
#    # 配置使用指定IP
#    ip-address: 127.0.0.1