#内置Endpoints
#auditevents	显示当前应用程序的审计事件信息
#beans	        显示应用Spring Beans的完整列表
#caches	        显示可用缓存信息
#conditions	    显示自动装配类的状态及及应用信息
#configprops	显示所有 @ConfigurationProperties 列表
#env	        显示 ConfigurableEnvironment 中的属性
#flyway	        显示 Flyway 数据库迁移信息
#health	        显示应用的健康信息（未认证只显示status，认证显示全部信息详情）
#heapdump	    返回一个GZip压缩的JVM堆dump
#httptrace	    显示HTTP跟踪信息（默认显示最后100个HTTP请求 - 响应交换）
#info	        显示任意的应用信息（在资源文件写info.xxx即可）
#liquibase	    展示Liquibase 数据库迁移
#logfile	    返回日志文件内容（如果设置了logging.file或logging.path属性的话），支持使用HTTP Range头接收日志文件内容的部分信息	Yes
#loggers	    显示和修改配置的loggers
#mappings	    显示所有 @RequestMapping 路径集列表
#metrics	    展示当前应用的 metrics 信息
#prometheus	    以可以被Prometheus服务器抓取的格式显示metrics信息
#scheduledtasks	显示应用程序中的计划任务
#sessions	    允许从Spring会话支持的会话存储中检索和删除用户会话。
#shutdown	    允许应用以优雅的方式关闭（默认情况下不启用）
#threaddump	    执行一个线程dump
management:
  #定义管理端点可用地址与端口
#  server:
#    port: 8081
#    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  #链路追踪，web地址端口：9411
  zipkin:
    baseUrl: ${zipkin.url:http://localhost:9400}
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0

javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true
  # Data source names to exclude from monitoring (optional, comma-separated)
  excluded-datasources: secretSource,topSecretSource
  # Enable monitoring of Spring services and controllers (optional, default: true)
  spring-monitoring-enabled: true
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests:
    log: true
    # to exclude images, css, fonts and js urls from the monitoring:
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # to aggregate digits in http requests:
    #http-transform-pattern: \d+
    # to add basic auth:
    #authorized-users: admin:pwd
    # to change the default storage directory:
    storage-directory: /tmp/${spring.application.name}
    # to change the default "/monitoring" path:
    #monitoring-path: /admin/performance