server:
  port: ${server.port.mq:8080}

spring:
  application:
    name: ${server.name.mq:mq}
  cloud:
    config:
      name: default,mq
  #链路追踪
  zipkin:
    baseUrl: ${zipkin.url:http://localhost:9411}
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      idle-timeout: 30000
      #expiry-timeout: 1000
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: rabbit_mq_default
    #支持发送端消息的确认与返回
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true