server:
  port: 8764

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  application:
    name: ${server.names.mq:mq_default}
  #配置中心
  cloud:
    config:
      #配置当不能连接配置服务器，则不能启动
      fail-fast: true
      #配置仓库分支
      label: master
      #配置文件的环境
      profile: test
      name: default,mq
      #使用uri或discovery
      #uri: http://localhost:8888/
      discovery:
        #开启配置服务发现
        enabled: true
        #注册中心的服务名
        service-id: config-server
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      idle-timeout: 30000
      #expiry-timeout: 1000
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: rabbit_mq_default
    #支持发送端消息的确认与返回
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true