server:
  port: ${server.port.mq:8080}

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-server.url:http://localhost:8760/eureka/}

spring:
  application:
    name: ${server.name.mq:mq}
  #配置中心
  cloud:
    config:
      fail-fast: true
      label: master
      profile: test
      name: default,mq
      discovery:
        enabled: true
        service-id: config-server
  #链路追踪
  zipkin:
    baseUrl: ${zipkin.url:http://localhost:9411}
  #日志追踪
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      idle-timeout: 30000
      #expiry-timeout: 1000
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: rabbit_mq_default
    #支持发送端消息的确认与返回
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true