server:
  port: 8764

# 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
    # 检索服务选项，当设置为true(默认值)时，会进行服务检索,注册中心不负责检索服务
    fetch-registry: true
    # 服务注册中心也会将自己作为客户端来尝试注册自己,为true（默认）时自动生效
    # register-with-eureka: false

spring:
  application:
    name: mq
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      idle-timeout: 30000
      #expiry-timeout: 1000
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: rabbit_mq_default
    #支持发送端消息的确认与返回
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true