server:
  port: ${server.port.job:8080}

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-server.url:http://localhost:8760/eureka/}

spring:
  application:
    name: ${server.name.job:job}
  #配置中心
  cloud:
    config:
      fail-fast: true
      label: master
      profile: test
      name: default,mq
      discovery:
        enabled: true
        service-id: config-server
  #链路追踪
  zipkin:
    baseUrl: ${zipkin.url:http://localhost:9411}
  #日志追踪
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0

zookeeper:
  url: 127.0.0.1
  port: 2181
  namespace: zk_job