server:
  port: ${server.port.job:8080}

spring:
  application:
    name: ${server.name.job:job}
  cloud:
    config:
      name: default,job
  #链路追踪
  zipkin:
    baseUrl: ${zipkin.url:http://localhost:9411}
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0

zookeeper:
  url: 127.0.0.1
  port: 2181
  namespace: zk_job