server:
  port: 10001

spring:
  application:
    name: ConfigCenterServer
  #配置读取本地文件
  profiles:
    active: native
  #配置基础的安全认证
  security:
    user:
      name: roy
      password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
