server:
  port: 10007

spring:
  application:
    name: ${server.name.api2:api2}
  profiles:
    include: base
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: rabbit_mq_default

#开启熔断机制
feign:
  hystrix:
    enabled: true
#服务熔断
hystrix:
  command:
    default:
      timeout:
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
#负载均衡
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 5000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
