server:
  port: 8762

spring:
  application:
    name: api2
  zipkin:
    baseUrl: http://localhost:8888
  cloud:
    config:
      # 配置当不能连接配置服务器，则不能启动
      fail-fast: true
      # 配置仓库分支
      label: master
      # 配置文件的环境
      profile: dev
      # 使用uri或discovery
#      uri: http://localhost:8888/
      discovery:
        #开启配置服务发现
        enabled: true
        #注册中心的服务名
        service-id: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

# 开启熔断机制
feign:
  hystrix:
    enabled: true

# 健康监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream