server:
  port: ${server.port.api2:8080}

spring:
  application:
    name: ${server.name.api2:api2}
  cloud:
    config:
      name: default,api2
  #链路追踪
  zipkin:
    baseUrl: ${zipkin.url:http://localhost:9411}
  #日志追踪
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: rabbit_mq_default

#开启熔断机制
feign:
  hystrix:
    # If true, an OpenFeign client will be wrapped with a Hystrix circuit breaker.
    enabled: true

#服务熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #熔断超时时长：6000ms
            timeoutInMilliseconds: 6000

#负载均衡
ribbon:
  #连接超时时间(ms)
  ConnectTimeout: 1000
  #通信超时时间(ms)，解决504问题
  ReadTimeout: 5000
  #是否对所有操作重试
  OkToRetryOnAllOperations: true
  #同一服务不同实例的重试次数
  MaxAutoRetriesNextServer: 2
  #同一实例的重试次数
  MaxAutoRetries: 1

#健康监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream