server:
  port: ${server.port.api2:8080}

spring:
  application:
    name: ${server.name.api2:api2}
  #链路追踪
  zipkin:
    baseUrl: ${zipkin.url:http://localhost:9411}
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: rabbit_mq_default

#开启熔断机制
feign:
  hystrix:
    enabled: true
#服务熔断
hystrix:
  command:
    default:
      timeout:
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
#负载均衡
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 5000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

#健康监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream